import React, { useEffect, useRef } from 'react';
import { gsap } from 'gsap';
import { DesignSystem } from '../../types';
import { getAccessibleColor } from '../../utils/accessibility';

interface BrandOverviewProps {
  system: DesignSystem;
  activeTheme: string;
}

export const BrandOverview: React.FC<BrandOverviewProps> = ({ system, activeTheme }) => {
  const sectionRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (sectionRef.current) {
      gsap.fromTo(
        sectionRef.current.children,
        { opacity: 0, y: 50 },
        {
          opacity: 1,
          y: 0,
          duration: 0.8,
          stagger: 0.1,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: sectionRef.current,
            start: 'top 85%',
            toggleActions: 'play none none none',
          },
        }
      );
    }
  }, []);

  const theme = system.themes[activeTheme];
  const textColor = getAccessibleColor(theme.textPrimary, theme.surface);
  const secondaryTextColor = getAccessibleColor(theme.textSecondary, theme.surface, '#E5E7EB', '#4B5563');

  return (
    <section ref={sectionRef} className="w-full">
      <div 
        className="glass-panel rounded-3xl p-12 md:p-16 flex flex-col items-center text-center shadow-2xl transition-colors duration-500"
        style={{
          background: theme.surface,
          color: textColor,
          borderColor: theme.border,
        }}
      >
        <h2 
          className="text-5xl md:text-7xl font-bold mb-6 tracking-tight"
          style={{ fontFamily: `"${system.typography?.displayFont?.name || 'Playfair Display'}", serif` }}
        >
          {system.brandName || 'Your Brand'}
        </h2>
        
        <p 
          className="text-xl md:text-2xl mb-12 max-w-2xl font-light"
          style={{ 
            fontFamily: `"${system.typography?.bodyFont?.name || 'Inter'}", sans-serif`,
            color: secondaryTextColor
          }}
        >
          {system.brandTagline || 'A beautiful design system generated by AI.'}
        </p>

        <div className="flex flex-wrap justify-center gap-3 mb-16">
          {(system.personality || ['Modern', 'Clean', 'Professional']).map((trait, index) => (
            <span 
              key={index}
              className="px-6 py-2 rounded-full text-sm font-medium tracking-wide uppercase"
              style={{
                background: theme.surfaceSecondary,
                color: theme.textSecondary,
                border: `1px solid ${theme.borderSubtle}`
              }}
            >
              {trait}
            </span>
          ))}
        </div>

        <div className="flex items-center justify-center gap-8">
          <ColorCircle color={system.colors?.primary?.hex || '#000000'} name="Primary" />
          <ColorCircle color={system.colors?.secondary?.hex || '#666666'} name="Secondary" />
          <ColorCircle color={system.colors?.accent?.hex || '#0071E3'} name="Accent" />
        </div>
      </div>
    </section>
  );
};

const ColorCircle = ({ color, name }: { color: string; name: string }) => (
  <div className="flex flex-col items-center group">
    <div 
      className="w-20 h-20 md:w-24 md:h-24 rounded-full shadow-lg mb-4 transform transition-transform duration-300 group-hover:scale-110"
      style={{ background: color }}
    />
    <span className="text-sm font-medium opacity-70">{name}</span>
  </div>
);
